### ISSUE TITLE
where is testing?

### ISSUE THREAD

**Issue by Pompeu** [jails-org/Jails#1]
nice  project but..., know test  cases are hard, but all frameworks have, jasmine  can help you in this.

**Comment by Javiani** [comment]
Hi Pompeu! Thank you for the feedback!
You're absolutely right, I cannot give any excuses, I'm already working on that, I'm studying jasmine and other frameworks to find which can fit in this project... 

I'm just after that!

**Comment by Pompeu** [comment]
cool, very nice

**Comment by Javiani** [comment]
Hi @Pompeu ! 
First, thanks for you contribution! 

I'm gonna close this because I just pushed the first very version of Testing Suite for Jails, it's living here: [https://github.com/jails-org/Tests](https://github.com/jails-org/Tests).

So, any concerns, issues and information about Jails Testing will be placed there =)

Thank you!
