### ISSUE TITLE
Error installing jails package on "NPM Install"

### ISSUE THREAD

**Issue by julionienow** [jails-org/Jails#3]
Hi,

I'm trying to run a repository wich have Jails JS as a dependency, but it dosnt work.

On the console it says that the reposity couldn`t be found.

I've tried to install with npm and even with yarn. Also have tried to delete package-lock and right now im out of ideas about what to do to fix this.

Here are some screenshots of the problem described

![picturemessage_2wkjziah uh2](https://user-images.githubusercontent.com/11317664/74371680-fac83480-4db7-11ea-9d83-67d300378a8f.png)
![picturemessage_w1ywszgo zrw](https://user-images.githubusercontent.com/11317664/74371684-fd2a8e80-4db7-11ea-9f77-0f002d66d430.png)

Thanks for your time

**Comment by Javiani** [comment]
Hey @julionienow , Oh my god man...

Those repositories were deprecated for a looong time, after a while I remove them from the project since Jails and dependencies had updated for further versions. There wasn't any reply on those repositories in the period they was deprecated or even when they were deleted.

Repositories can be reverted within 90 days after deleted, so I was sure that no one was actually working with it.

If you still needing those repositories, please, try to find  them some local node_modules and send them back to me so I can create them here ok?

Unfortunately, I couldn't restore them using github and I can't find them on my machine anymore.

**Comment by Javiani** [comment]
Hey @julionienow ,

I feel really bad for you, I was not aware that somebody was using those repositories... 
I'm trying to get in touched with github team, maybe we can recover those respos... 🤞

**Comment by Javiani** [comment]
Hey @julionienow,

Can you please try your build again? 
Thanks to Github Team ❤️  those repositories was restored again 🎉 

Please, get back to me once you tested  just for to know that it´s working as expected.

Thanks

**Comment by mariozuany** [comment]
@Javiani omg man. Thank you so much!

**Comment by julionienow** [comment]
Hi @Javiani, it worked! Now i'm able to install the project again.
Thank you for the effort
Best regards
